### ISSUE TITLE
Exception using [BackgroundService]

### ISSUE THREAD

**Issue by Thundarr1974** [andreas-soroko/sorovi.DependencyInjection.AutoRegister#3]
Cool library! Found an issue here:

https://github.com/andreas-soroko/sorovi.DependencyInjection.AutoRegister/blob/718ed1354eb1c515705065412293854413e39812/sorovi.DependencyInjection.AutoRegister/ServiceCollectionExtension.cs#L126

Changing it to .AddHostedService with the actual type from the Tuple seems to resolve it.

**Comment by andreas-soroko** [comment]
Hi @Thundarr1974,

could you shortly explain what issue did you faced there?

**Comment by Thundarr1974** [comment]
> Hi @Thundarr1974,
> 
> could you shortly explain what issue did you faced there?

When using [BackgroundService], an exception is thrown from the line I mentioned in the issue b/c it's attempting to use the typeInfo tuple to register a Singleton. I did a local test replacing it with .AddHostedService() using typeInfo.Type.

**Comment by andreas-soroko** [comment]
Hey, 

could you give v1.0.1 a try? I Couldn't reproduce your issue, but I use now `AddTransient` as `AddHostedService` does.
If the Exception still occurs, could you provide more information about it? 

Like:  
- what kind of exception gets thrown?
- small example to reproduce?

**Comment by Thundarr1974** [comment]
> Hey,
> 
> could you give v1.0.1 a try? I Couldn't reproduce your issue, but I use now `AddTransient` as `AddHostedService` does. If the Exception still occurs, could you provide more information about it?
> 
> Like:
> 
> * what kind of exception gets thrown?
> * small example to reproduce?

Hi - thanks for looking at this. It technically works, but I would point out that AddHostedService does not call AddTransient (at least not in net6.0). See
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/ServiceCollectionHostedServiceExtensions.cs

**Comment by andreas-soroko** [comment]
better late than never :)

The new version is now using reflection to get the `AddHostedService` method, so should now be right in every situation.
